name: ci
on: [push, pull_request, workflow_dispatch]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'
          cache-dependency-path: requirements.txt

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Print tool versions
        run: |
          python -V
          pip -V
          python - <<'PY'
          from importlib.metadata import version
          import fastapi, starlette, prometheus_client as pc
          print("fastapi", fastapi.__version__)
          print("starlette", starlette.__version__)
          print("prometheus-client", version("prometheus-client"))
          print("prometheus_client.__file__", pc.__file__)
          PY

      - name: Run tests
        env:
          PYTHONPATH: app
        run: pytest -q
