name: ci

on:
  push:
  pull_request:
  workflow_dispatch:
    inputs:
      debug_versions:
        description: "Print tool versions step"
        required: false
        default: "0"   # pass 1 to enable

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.11", "3.12"]
    env:
      PYTHONPATH: app
      DEBUG_VERSIONS: ${{ github.event.inputs.debug_versions || '0' }}
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: pip
          cache-dependency-path: requirements.txt

      - name: Install deps
        run: |
          python -m pip install -U pip
          pip install -r requirements.txt
          pip install pytest-cov

      - name: Print tool versions
        if: env.DEBUG_VERSIONS == '1'
        run: |
          python -V
          pip -V
          python - <<'PY'
          from importlib.metadata import version
          import fastapi, starlette, prometheus_client as pc
          print("fastapi", fastapi.__version__)
          print("starlette", starlette.__version__)
          print("prometheus-client", version("prometheus-client"))
          print("prometheus_client.__file__", pc.__file__)
          PY

      - name: Run tests (with coverage)
        run: pytest -q --cov=app --cov-report=term-missing --cov-report=xml

      - name: Upload coverage.xml
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ matrix.python-version }}
          path: coverage.xml
