name: ci

on:
  push:
  pull_request:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip -V
          python -m pip install -U pip
          pip install -r requirements.txt

      - name: Print tool versions
        run: |
          python -V
          pip -V
          python - <<'PY'
          import sys
          import fastapi, starlette
          print("fastapi", fastapi.__version__)
          print("starlette", starlette.__version__)
          print("sys.path[0]", sys.path[0])
          PY

      - name: Run tests
        env:
          PYTHONPATH: app
        run: pytest -q
